
import "../styles/globals.scss";
import Navbar from "@/components/navbar/header";
import { ThemeProvider } from "@/hooks/useTheme";
import ModalComponent from "@/components/modal/modal";
import Login from "@/components/navbar/loginComponent";
export const metadata = {
  title: "Desert Color Usa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
