
import "../styles/globals.scss";
import Navbar from "@/components/navbar/header";
import { ThemeProvider } from "@/hooks/useTheme";
import ModalComponent from "@/components/modal/modal";
import Login from "@/components/navbar/loginComponent";
import {Providers} from '../store/StoreProvider'
export const metadata = {
  title: "Desert Color Usa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
